/*
 * k8l
 *
 * Kubernetes light logs API
 *
 * API version: 1.0
 * Contact: mogui83@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetNamespaceLogs - Logs for a namespace
func GetNamespaceLogs(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetResourceLogs - Logs for a container
func GetResourceLogs(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
