apiVersion: apps/v1
kind: Deployment
metadata:
  name: testecho
spec:
  replicas: 1
  selector:
      matchLabels:
        app: testecho
  template:
    metadata:
      labels:
        app: testecho
    spec:
      containers:
      - image: ealen/echo-server:latest
        imagePullPolicy: IfNotPresent
        name: testecho
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: testecho
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
  selector:
    app: testecho
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: testecho
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: echo.cluster.local
      http:
        paths:
          - path: /echo
            backend:
              serviceName: testecho
              servicePort: 5000